export const ActionTypes = {
    SET_POKEMON: "SET_POKEMON",
    SET_POKEDATA: "SET_POKEDATA",
    SELECT_POKEMON: "SELECT_POKEMON",
    SET_OFFSET: "SET_OFFSET",
    SET_POKEMON_DETAIL: "SET_POKEMON_DETAIL",
    SET_POKEDATA_DETAIL: "SET_POKEDATA_DETAIL",
}